development:
  clients:
    default:
      database: <%= ENV['MONGOLAB_URI'] %>
      hosts:
        - localhost:27017
      options:
  options:
test:
  clients:
    default:
      database: autofin_rails_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  clients:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
